export type IconName = keyof typeof iconMap;

export const iconMap = {
  Apple: ['fruta', 'comida', 'supermercado', 'manzana', 'verduleria'],
  Baby: ['bebé', 'hijos', 'familia', 'pañales', 'guardería'],
  BadgePercent: ['descuento', 'oferta', 'porcentaje', 'compras'],
  Banknote: ['dinero', 'efectivo', 'billete', 'salario'],
  Bath: ['baño', 'bañera', 'higiene', 'relax'],
  Bean: ['café', 'comida', 'grano', 'bebida'],
  Bed: ['cama', 'muebles', 'hogar', 'decoración', 'dormitorio'],
  Bike: ['bicicleta', 'transporte', 'ejercicio', 'ciclismo'],
  Bitcoin: ['criptomonedas', 'inversión', 'dinero', 'crypto'],
  Bone: ['mascota', 'perro', 'comida de animal'],
  BookOpen: ['libros', 'educación', 'estudios', 'universidad', 'colegio'],
  BookUser: ['contactos', 'agenda', 'social'],
  Brain: ['salud mental', 'terapia', 'psicologo'],
  Briefcase: ['trabajo', 'negocios', 'oficina', 'empleo', 'sueldo'],
  Brush: ['limpieza', 'hogar', 'productos de limpieza', 'cepillo'],
  Building2: ['edificio', 'oficina', 'apartamento', 'empresa'],
  Bus: ['autobús', 'transporte público', 'colectivo', 'boleto'],
  Cake: ['torta', 'postre', 'pasteleria', 'dulces', 'cumpleaños'],
  Camera: ['foto', 'fotografía', 'hobby', 'cámara'],
  Candy: ['golosinas', 'dulces', 'kiosco'],
  Car: ['coche', 'auto', 'transporte', 'vehículo', 'gasolina'],
  Caravan: ['casa rodante', 'viaje', 'vacaciones', 'camping'],
  Cat: ['gato', 'mascota', 'animal'],
  ChefHat: ['cocina', 'chef', 'restaurante', 'comida'],
  Church: ['iglesia', 'donación', 'religión'],
  Cigarette: ['tabaco', 'cigarrillos', 'vicios'],
  CigaretteOff: ['dejar de fumar', 'salud', 'vicios'],
  Clapperboard: ['cine', 'película', 'video'],
  Coffee: ['café', 'bebida', 'desayuno', 'starbucks'],
  Coins: ['monedas', 'dinero', 'ahorro', 'inversión'],
  CookingPot: ['cocina', 'olla', 'comida', 'hogar'],
  CreditCard: ['tarjeta de crédito', 'pagos', 'compras', 'deudas'],
  Crop: ['jardinería', 'plantas', 'huerta', 'agricultura'],
  Cross: ['salud', 'farmacia', 'cruz roja'],
  CupSoda: ['bebida', 'gaseosa', 'refresco'],
  Dog: ['perro', 'mascota', 'animal'],
  DollarSign: ['dolar', 'dinero', 'moneda', 'finanzas'],
  Drama: ['teatro', 'actuación', 'entretenimiento', 'cultura'],
  Droplets: ['agua', 'factura de servicios', 'gotas'],
  Dumbbell: ['gimnasio', 'deporte', 'ejercicio', 'fitness', 'entrenamiento'],
  Euro: ['euro', 'dinero', 'moneda', 'finanzas'],
  FerrisWheel: ['parque de diversiones', 'entretenimiento', 'feria'],
  FileText: ['documento', 'archivo', 'texto', 'contrato', 'informe'],
  Film: ['cine', 'películas', 'series', 'entretenimiento', 'streaming'],
  Fish: ['pescado', 'comida', 'mascota', 'pesca'],
  Flame: ['gas', 'factura de servicios', 'fuego'],
  Flower: ['flores', 'regalo', 'jardinería'],
  Fuel: ['gasolina', 'combustible', 'nafta', 'estación de servicio'],
  Gamepad2: ['juegos', 'videojuegos', 'gaming', 'playstation', 'xbox'],
  Gift: ['regalo', 'presente', 'obsequio', 'cumpleaños'],
  Glasses: ['lentes', 'optica', 'salud', 'anteojos'],
  GraduationCap: ['educación', 'estudios', 'universidad', 'graduación', 'curso'],
  Grape: ['uva', 'fruta', 'vino', 'comida'],
  Guitar: ['guitarra', 'música', 'hobby', 'instrumento'],
  Hammer: ['herramientas', 'reparación', 'construcción'],
  HandCoins: ['donación', 'caridad', 'dar', 'ayuda'],
  HandHeart: ['donación', 'amor', 'caridad', 'ayuda voluntaria'],
  Headphones: ['música', 'auriculares', 'audio', 'podcast'],
  HeartPulse: ['salud', 'medico', 'doctor', 'hospital', 'farmacia'],
  Home: ['casa', 'hogar', 'vivienda', 'alquiler', 'hipoteca'],
  IceCream: ['helado', 'postre', 'dulce'],
  Joystick: ['juegos', 'videojuegos', 'arcade', 'entretenimiento'],
  Key: ['llaves', 'cerrajero', 'casa'],
  Keyboard: ['teclado', 'computadora', 'trabajo', 'oficina'],
  Lamp: ['lámpara', 'luz', 'iluminación', 'hogar', 'decoración'],
  Landmark: ['impuestos', 'gobierno', 'banco', 'oficial', 'trámites'],
  Laptop: ['tecnología', 'electrónica', 'computadora', 'trabajo'],
  Leaf: ['naturaleza', 'ecología', 'plantas', 'jardín'],
  Library: ['biblioteca', 'libros', 'estudios'],
  Martini: ['bebidas', 'bar', 'alcohol', 'copas', 'salida'],
  Microwave: ['electrodomésticos', 'cocina', 'hogar'],
  MousePointer: ['computadora', 'internet', 'trabajo', 'click'],
  Music: ['música', 'concierto', 'canciones', 'spotify'],
  Package: ['paquete', 'envío', 'correo', 'compras online'],
  PackageCheck: ['entrega', 'recibido', 'paquete', 'envío'],
  Paintbrush: ['arte', 'pintura', 'hobby', 'decoración'],
  ParkingCircle: ['estacionamiento', 'parking', 'coche'],
  ParkingSquare: ['estacionamiento', 'auto', 'coche', 'parking'],
  PartyPopper: ['fiesta', 'celebración', 'evento'],
  PawPrint: ['mascotas', 'perro', 'gato', 'animales', 'veterinario'],
  Phone: ['teléfono', 'celular', 'factura de móvil', 'comunicación'],
  PiggyBank: ['ahorros', 'inversiones', 'dinero', 'finanzas'],
  Pill: ['medicamentos', 'farmacia', 'salud', 'pastilla'],
  Pizza: ['comida rápida', 'pizza', 'delivery', 'restaurante'],
  Plane: ['viaje', 'avion', 'vacaciones', 'turismo', 'vuelo'],
  Plug: ['electricidad', 'luz', 'factura de servicios', 'enchufe'],
  Popcorn: ['pochoclo', 'cine', 'snack'],
  Puzzle: ['rompecabezas', 'juegos', 'hobby', 'entretenimiento'],
  Receipt: ['factura', 'recibo', 'cuentas', 'servicios', 'luz', 'agua', 'gas'],
  Recycle: ['reciclaje', 'ecología', 'medio ambiente', 'basura'],
  Router: ['internet', 'wifi', 'tecnología'],
  Sailboat: ['barco', 'navegar', 'vacaciones', 'mar'],
  Salad: ['ensalada', 'comida saludable', 'vegetales', 'dieta'],
  Sandwich: ['sándwich', 'comida rápida', 'almuerzo'],
  Scale: ['legal', 'justicia', 'balance', 'leyes'],
  School: ['escuela', 'colegio', 'educación', 'niños'],
  Scissors: ['peluquería', 'corte de pelo', 'estética', 'tijeras'],
  ShieldCheck: ['seguro', 'protección', 'seguridad', 'garantía'],
  Shirt: ['ropa', 'camiseta', 'prenda', 'vestir', 'tienda'],
  ShoppingBag: ['compras', 'tienda', 'bolsa', 'mandado', 'supermercado'],
  ShoppingBasket: ['canasta', 'supermercado', 'compras', 'mercado'],
  ShowerHead: ['ducha', 'baño', 'agua', 'higiene'],
  Smile: ['bienestar', 'felicidad', 'emociones', 'ocio'],
  Smartphone: ['teléfono', 'celular', 'móvil', 'app'],
  Sofa: ['muebles', 'hogar', 'decoración', 'living'],
  Sprout: ['planta', 'crecimiento', 'jardinería', 'naturaleza'],
  Stethoscope: ['salud', 'doctor', 'médico', 'consulta'],
  Store: ['tienda', 'compras', 'almacén'],
  Tent: ['camping', 'viaje', 'vacaciones', 'naturaleza'],
  Ticket: ['entradas', 'evento', 'cine', 'concierto', 'teatro'],
  ToyBrick: ['juguetes', 'niños', 'regalo'],
  Train: ['tren', 'subte', 'metro', 'transporte', 'viaje'],
  TrainFront: ['tren', 'subte', 'metro', 'viaje'],
  Trees: ['parque', 'naturaleza', 'jardinería'],
  TrendingDown: ['pérdidas', 'decrecimiento', 'inversiones', 'acciones'],
  TrendingUp: ['inversiones', 'crecimiento', 'ganancias', 'acciones'],
  Trophy: ['premio', 'competencia', 'deporte'],
  Truck: ['camión', 'transporte', 'envío', 'mudanza'],
  Tv: ['televisión', 'electrodomésticos', 'entretenimiento', 'streaming'],
  Umbrella: ['seguro', 'protección', 'lluvia'],
  University: ['universidad', 'educación', 'estudios'],
  User: ['perfil', 'usuario', 'personal', 'cuenta'],
  Users: ['grupo', 'equipo', 'social', 'amigos'],
  Utensils: ['comida', 'restaurante', 'cubiertos', 'almuerzo', 'cena'],
  Wallet: ['billetera', 'dinero', 'efectivo'],
  WalletCards: ['billetera', 'tarjetas', 'crédito', 'débito'],
  Warehouse: ['almacén', 'depósito', 'compras', 'mayorista'],
  WashingMachine: ['lavandería', 'lavarropas', 'electrodomésticos'],
  Watch: ['reloj', 'accesorios', 'regalo'],
  Wifi: ['internet', 'conexión', 'factura de servicios', 'router'],
  Wine: ['vino', 'bebida', 'alcohol', 'cena'],
  Wrench: ['servicios', 'reparaciones', 'herramientas', 'facturas', 'mantenimiento'],
};
