name: fintouch_flutter
publish_to: "none"
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
